spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:jpa
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
